### ISSUE TITLE
The dataloader is yet to be released -- correct?

### ISSUE THREAD

**Issue by pinakinathc** [yfeng95/DELTA#3]
hi
great work !! This seems relevant to me. I suppose the dataloader is yet to be released? Or am I missing something.

```
from .dataset import build_dataset
ModuleNotFoundError: No module named 'lib.dataset'
```

thanks.

**Comment by yfeng95** [comment]
Hey thanks for the question! 

I forgot to upload the dataset folder,  just added, please pull and check again, thanks! 

Best,
Yao

**Comment by pinakinathc** [comment]
Thank you for uploading the dataset folder.
